// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrwxqdunhjxmzszspmol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyd3hxZHVuaGp4bXpzenNwbW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTIxNzksImV4cCI6MjA3MjQyODE3OX0.ompnzOPAE0outu7HY6kkveCWsPjHyCOz6l5yldPrSWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});